# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab8a9e1996b3eb1eeb141054e431aadfa7f0f1eaa5e4d59b9922ffcdaf753f8d7d776f730962bfd530d352dca8c2005fbc39b5d9b1f79bce79c212487c3f498a

test:
  secret_key_base: feb05bd144b6aa87660543e5af27007d1c19863c5a6309780147b9684548a4291f397ad8d007111dc9a26b4296c6a1977ebd81201a62ac5d9ff00de898777542

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
